CREATE TABLE IF NOT EXISTS plantas_metricas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    planta_id VARCHAR(50) NOT NULL UNIQUE,
    visualizacoes INT DEFAULT 1,
    ultima_visualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
